### ISSUE TITLE
記事執筆に先立って事前準備が必要なものをドキュメントする

### ISSUE THREAD

**Issue by kentaro** [elixirjp-slack-com/realworld_phoenix_liveview#5]
PostgreSQLを入れてなかったので、以下の通りエラーが出てしまいました。この件も含め、準備に必要なものを記事にも書いていくことになりそう。というか、事前準備をいちいち書いてるとキリがないかもなので、Dockerでやる方がいいですかねー。

```
$ mix ecto.setup

（省略）

16:24:02.439 [error] GenServer #PID<0.5102.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol

16:24:02.443 [error] GenServer #PID<0.5108.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.4.0) lib/db_connection/connection.ex:100: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for RealworldPhoenixLiveview.Repo couldn't be created: killed
```

**Comment by tamanugi** [comment]
Postgresを自前でインストールしてもらうか、もしくはdockerで起動してもらうかを読者に選んでもらえるようにするといいかもですね 🤔 

僕はいつも以下のような `docker-compose.yml` を配置して開発しているので、必要ならその旨を記載しようかなと思っていました (Phoenixインストールの流れで)

```yml
version: "3.7"
services:
  dbms:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
```
